version: "3"
services:
    db:
        image: postgres:latest
        container_name: postgres
        restart: always
        ports:
            - "9999:9999"
        environment:
            POSTGRES_USER: "${DB_USER_ID}"
            POSTGRES_PASSWORD: "${DB_USER_PASSWORD}"
            TZ: "Asia/Seoul"
        volumes:
            - ${POSTGRES_HOME_DIR}/data/:/var/lib/postgresql/data
