FROM postgres:13.1

#초기 DB만들기
ENV POSTGRES_DB=udr_db
ENV POSTGRES_USER=udr
ENV POSTGRES_PASSWORD=tjqjthvmxmdnpdj

RUN apt-get update \
      && apt-get install -y --no-install-recommends \
            postgresql-13-postgis-3 \
			postgresql-13-postgis-3-scripts \
      && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /docker-entrypoint-initdb.d

#INIT DUMP 복원시 사용 , 복원안할시 주석
COPY ./init_dump.sql /docker-entrypoint-initdb.d/
